// src/sw.js
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst } from 'workbox-strategies'
import { skipWaiting, clientsClaim } from 'workbox-core'

// The app is auto-update (`registerType: 'autoUpdate'`). Without these, an
// installed PWA can keep serving the old app shell for days until a full reload,
// which made users see stale features and think deploys "didn't take". Activating
// the new SW immediately fixes that.
skipWaiting()
clientsClaim()
cleanupOutdatedCaches()

// Serve navigation requests network-first so the latest JS/HTML is always
// fetched on load (falling back to cache only when offline). Prevents stale
// builds sticking around and showing old features after a deploy. No
// networkTimeoutSeconds here: on slow connections a timeout would serve a
// stale index.html that references removed hashed assets, blanking the app.
// This route must be registered BEFORE precacheAndRoute so it wins over the
// precached app shell for navigations.
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({ cacheName: 'app-shell' })
)

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// ─── Push Notification Handler ───
self.addEventListener('push', (event) => {
  if (!event.data) return

  let data
  try {
    data = event.data.json()
  } catch {
    return
  }

  const { point, subject, id, isQuestion, type, title: broadcastTitle, message, broadcastId } = data

  if (type === 'broadcast') {
    const options = {
      body: message,
      icon: '/pwa-192x192.png',
      tag: `broadcast-${broadcastId}`,
      renotify: true,
      requireInteraction: true,
      vibrate: [200, 100, 200],
      data: { url: '/', broadcastId },
      actions: [
        { action: 'open', title: 'Open App' },
        { action: 'dismiss', title: 'Dismiss' },
      ],
    }
    event.waitUntil(self.registration.showNotification(broadcastTitle || '📢 Announcement', options))
    return
  }

  const options = {
    body: point,
    icon: '/pwa-192x192.png',
    tag: `keypoint-${id}`,
    renotify: true,
    requireInteraction: true,
    vibrate: [200, 100, 200],
    data: {
      url: '/',
      pointId: id,
      subject,
    },
    actions: [
      { action: 'open', title: 'Open App' },
      { action: 'dismiss', title: 'Dismiss' },
    ],
  }

  const title = isQuestion
    ? `📝 Quick Question — ${subject}`
    : `📚 247 Chops — ${subject}`

  event.waitUntil(self.registration.showNotification(title, options))
})

// ─── Notification Click Handler ───
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  if (event.action === 'dismiss') return

  event.waitUntil(
    clients.matchAll({ type: 'window' }).then((clientList) => {
      // If a window is already open, focus it
      for (const client of clientList) {
        if (client.url && 'focus' in client) {
          return client.focus()
        }
      }
      // Otherwise open new window
      if (clients.openWindow) {
        return clients.openWindow('/')
      }
    })
  )
})

// ─── Caching strategies for app data ───
registerRoute(({ url }) => url.pathname.startsWith('/api/'), new NetworkFirst({ cacheName: 'api-cache' }))