// src/sw.js
import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst } from 'workbox-strategies'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// ─── Push Notification Handler ───
self.addEventListener('push', (event) => {
  if (!event.data) return

  let data
  try {
    data = event.data.json()
  } catch {
    return
  }

  const { point, subject, id, isQuestion, type, title: broadcastTitle, message, broadcastId } = data

  if (type === 'broadcast') {
    const options = {
      body: message,
      icon: '/pwa-192x192.png',
      tag: `broadcast-${broadcastId}`,
      renotify: true,
      requireInteraction: true,
      vibrate: [200, 100, 200],
      data: { url: '/', broadcastId },
      actions: [
        { action: 'open', title: 'Open App' },
        { action: 'dismiss', title: 'Dismiss' },
      ],
    }
    event.waitUntil(self.registration.showNotification(broadcastTitle || '📢 Announcement', options))
    return
  }

  const options = {
    body: point,
    icon: '/pwa-192x192.png',
    tag: `keypoint-${id}`,
    renotify: true,
    requireInteraction: true,
    vibrate: [200, 100, 200],
    data: {
      url: '/',
      pointId: id,
      subject,
    },
    actions: [
      { action: 'open', title: 'Open App' },
      { action: 'dismiss', title: 'Dismiss' },
    ],
  }

  const title = isQuestion
    ? `📝 Quick Question — ${subject}`
    : `📚 Key Point — ${subject}`

  event.waitUntil(self.registration.showNotification(title, options))
})

// ─── Notification Click Handler ───
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  if (event.action === 'dismiss') return

  event.waitUntil(
    clients.matchAll({ type: 'window' }).then((clientList) => {
      // If a window is already open, focus it
      for (const client of clientList) {
        if (client.url && 'focus' in client) {
          return client.focus()
        }
      }
      // Otherwise open new window
      if (clients.openWindow) {
        return clients.openWindow('/')
      }
    })
  )
})

// ─── Caching strategies for app data ───
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({ cacheName: 'api-cache' })
)